version: "3.7"

networks:
  droplt:
    external:
      name: droplt

services:
  mariadb:
    image: mariadb:latest
    volumes:
      # where mariadb stores databases
      - ${BASE_PATH}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      droplt:
        aliases:
          - droplt-db
    ports:
      - 3306:3306
  transmission:
    image: linuxserver/transmission:latest
    volumes:
      # where transmission stores torrents downloads
      - ${BASE_PATH}/transmission-downloads:/downloads
      # where transmission stores its configuration, logs files
      - ${BASE_PATH}/transmission-config:/config
      # where transmission listen for .torrent files to add
      - ${BASE_PATH}/transmission-watch:/watch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - USER=${BT_USER}
      - PASS=${BT_PASSWORD}
    networks:
      droplt:
        aliases:
          - droplt-transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  filebot:
    image: jlesage/filebot
    volumes:
      # where filebot find files that must be accessible by the application
      - ${BASE_PATH}:/storage
      # where filebot stores its configuration, logs files
      - ${BASE_PATH}/filebot-config:/config
      # where filebot AMC (Automated Media Center) script find input files
      - ${BASE_PATH}/transmission-downloads/complete:/watch
      # where filebot AMC output organized files
      - ${BASE_PATH}/filebot-output:/output
    environment:
      - AMC_INTERVAL=300
      - AMC_ACTION=symlink
      - AMC_ARTWORK=n
      - AMC_PROCESS_MUSIC=f
  jackett:
    image: linuxserver/jackett
    volumes:
      # where jackett stores its configuration, logs files
      - ${BASE_PATH}/jackett-config:/config
      # where jackett download .torrent files
      - ${BASE_PATH}/transmission-watch:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    networks:
      droplt:
        aliases:
          - droplt-jackett
    ports:
      - 9117:9117
  plex:
    image: plexinc/pms-docker
    network_mode: host
    volumes:
      # where plex stores configuration data
      - ${BASE_PATH}/plex-config:/config
      # where plex stores transcoder temp files
      - ${BASE_PATH}/plex-transcode:/transcode
      # where plex find medias (output from filebot)
      - ${BASE_PATH}/filebot-output:/data
      # where plex find real medias (needed due to symlinks)
      - ${BASE_PATH}/transmission-downloads/complete:/watch
